# Generated by Django 5.1 on 2024-09-29 05:54

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20240929_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiOccurencesTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('every_week', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=list, size=None)),
                ('every_month', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=list, size=None)),
                ('every_last_day_of_month', models.BooleanField(default=False)),
                ('every_year', django.contrib.postgres.fields.hstore.HStoreField()),
                ('number_a_day', models.SmallIntegerField(blank=True, null=True)),
                ('number_a_week', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
