# Generated by Django 5.1 on 2024-09-29 15:56

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_multioccurencestask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multioccurencestask',
            name='every_year',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
