# Generated by Django 5.1 on 2024-09-29 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_multioccurencestask_every_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multioccurencestask',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multioccurencestask',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
            preserve_default=False,
        ),
    ]
