# Generated by Django 5.1 on 2024-10-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_multioccurencestask_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multioccurencestask',
            name='every_year',
            field=models.JSONField(default=list),
        ),
    ]
