# Generated by Django 5.1 on 2024-10-06 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_multioccurencestask_every_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='datedtask',
            name='related_mot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.multioccurencestask'),
        ),
    ]
