# Generated by Django 5.1 on 2024-10-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_datedtask_related_mot'),
    ]

    operations = [
        migrations.AddField(
            model_name='multioccurencestask',
            name='task_name',
            field=models.CharField(default='task', max_length=100),
            preserve_default=False,
        ),
    ]
