# Generated by Django 5.1 on 2024-11-08 06:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_multioccurencestask_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multioccurencestask',
            name='every_month',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='multioccurencestask',
            name='every_week',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, default=list, size=None),
        ),
    ]
