# Generated by Django 5.1 on 2024-12-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_multioccurencestask_every_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='datedtask',
            name='label',
            field=models.ManyToManyField(to='task.label'),
        ),
        migrations.AddField(
            model_name='multioccurencestask',
            name='label',
            field=models.ManyToManyField(to='task.label'),
        ),
        migrations.AddField(
            model_name='weektask',
            name='label',
            field=models.ManyToManyField(to='task.label'),
        ),
    ]
