# Generated by Django 5.1 on 2025-01-07 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_label_datedtask_label_multioccurencestask_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weektask',
            name='related_mot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.multioccurencestask'),
        ),
    ]
